services:
  postgres:
    image: postgres:18-alpine
    environment:
      POSTGRES_DB: "yukumichi"
      POSTGRES_USER: "yukumichi"
      POSTGRES_PASSWORD: "yukumichi"
      TZ: UTC
    command:
      - "postgres"
      - "-c"
      - "log_statement=all"
      - "-c"
      - "timezone=UTC"
    ports:
      - "5432:5432"
    volumes:
      - yukumichi_postgres_data:/var/lib/postgresql

volumes:
  yukumichi_postgres_data:
