services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: "sanpo"
      POSTGRES_USER: "sanpo"
      POSTGRES_PASSWORD: "sanpo"
      TZ: UTC
    command:
      - "postgres"
      - "-c"
      - "log_statement=all"
      - "-c"
      - "timezone=UTC"
    ports:
      - "5432:5432"
    volumes:
      - sanpo_postgres_data:/var/lib/postgresql/data

volumes:
  sanpo_postgres_data:
