packages:
  - "apps/*"
  - "packages/*"
verifyDepsBeforeRun: install
# Allow to install packages only after 7 days (10080 minutes) from their release.
minimumReleaseAge: 10080
# List of packages to exclude from minimumReleaseAge check with description of why they are excluded.
minimumReleaseAgeExclude: []
allowBuilds:
  cpu-features: true
  esbuild: true
  msw: true
  protobufjs: true
  sharp: true
  ssh2: true
  unrs-resolver: true
  workerd: true
catalog:
  eslint: 9.39.3
  "@faker-js/faker": ^10.4.0
  vitest: ^4.1.2
  "@vitest/browser": ^4.1.2
  "@vitest/browser-playwright": ^4.1.2
  "@vitest/eslint-plugin": ^1.6.13
  prettier: ^3.8.1
  knip: ^6.0.6
  typescript: 5.9.3
  "@types/node": 24.11.0
  zod: "^4.3.6"
  hono: ^4.12.5
  msw: ^2.14.6
  "eslint-plugin-boundaries": ^6.0.2
  "eslint-import-resolver-typescript": ^4.4.4
